### ISSUE TITLE
Publishing several document types at the same scheduled time results in document types not being saved in the cache

### ISSUE THREAD

**Issue by RasmusUmbraco** [umbraco/Umbraco.Deploy.Issues#98] opened 2022-01-12 10:55 UTC
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17

### Bug summary

Using the schedule feature to publish more document types at the same time will publish all the document types, but only save the first document type in the cache.

### Steps to reproduce

Use the scheduling feature to schedule publishing of more than one document type at the same date and time.
![image](https://user-images.githubusercontent.com/88326257/149126369-40c41716-460a-4810-b9db-421e499451a5.png)

First document type - published and cached:
![image](https://user-images.githubusercontent.com/88326257/149126789-d1bf18ee-18e6-4828-abc8-c116af31aaca.png)

Second document type - published but not cached:
![image](https://user-images.githubusercontent.com/88326257/149126838-02842c21-a1e7-4c01-af4e-fe3f96b65a69.png)

I have reproduced this on V8.15 as well.

**Comment by AndyButland** [comment] 2022-01-13 16:23
This looks to be a duplicate of [this issue](https://github.com/umbraco/Umbraco.Cloud.Issues/issues/411), which had a bit of discussion but no firm resolution.  From the comments there though, this looks to be occurring in a feature that's little used and can almost certainly be disabled.  See specifically [this comment](https://github.com/umbraco/Umbraco.Cloud.Issues/issues/411#issuecomment-709222714).

I can confirm have also been able to replicate the problem, and assuming that you aren't using the ["Live Edit" feature](https://our.umbraco.com/documentation/Umbraco-Cloud/Set-up/working-with-uaas-cli/), can confirm adding this to the `web.config` file resolves the issue:

```
<add key="UmbracoCloud.LiveEditingEnabled" value="false" />
```

**Comment by tombille** [comment] 2022-01-14 10:18
@AndyButland @nul800sebastiaan 

Yeah, this setting has resolved the issue.

`<add key="UmbracoCloud.LiveEditingEnabled" value="false" />`

**Comment by AndyButland** [comment] 2022-01-14 11:00
Thanks - in which case will close, given this feature does seem to be little used now, and is removed in V9.  For V8 the solution to the issue will be to add this setting.  We can't just remove the feature of course just in case there are some people that do use it.

**Closed by AndyButland** 2022-01-14 11:00 UTC
Labels: type/bug

**Comment by AndyButland** [comment] 2022-01-17 07:37
I've also arranged with the next patch release of Umbraco Deploy to avoid the exception when this feature is enabled and scheduled publishing is used (which happens on a background thread and leads to the null reference).
