### ISSUE TITLE
Failure during UmbracoForms prevalue source deployment

### ISSUE THREAD

**Issue by idseefeld** [umbraco/Umbraco.Deploy.Issues#23] opened 2020-04-09 13:36 UTC
I tried to deploy a prevalue source from the Forms section to Umbraco Cloud and got an error.
Using Umbraco version 8.6.0, Forms version 8.4.0 and Deploy version 3.4.2

What I did:

1. I have created a drop-down data type in _Settings_ section.
2. Added a _Prevalue Source_ in _Forms_ section based on this data type.
3. Queued the new prevalue source.
4. Clicked _Send changes to the Development workspace_ button on Content section dashboard.
5. Deployment failed.

These are the technical details of the failure:

```
f8dfb9f1 - Executing, 10%
f8dfb9f1 - Executing, 10% - Get remote session
f8dfb9f1 - Executing, 20% - Create manifest on source
f8dfb9f1 - Executing, 25% - Review manifest on target
f8dfb9f1 - Executing, 28% - Negotiate files transfer.
f8dfb9f1 - Executing, 30% - Create package on source
f8dfb9f1 - Executing, 32% - Transfer 0 files.
f8dfb9f1 - Executing, 32% - Complete local session
f8dfb9f1 - Executing, 35% - Process package on target
f8dfb9f1 - Executing, 80% - Exception!
f8dfb9f1 - Executing, 80% - Abort remote session
f8dfb9f1 - Failed, 80% - Total time 00:00:01.824.

-- EXCEPTION ---------------------------------------------------
 (proper exception traces at the end of this log)
System.InvalidOperationException: Don't know how to map Umbraco.Deploy.Forms.Artifacts.PreValueSourceArtifact to Umbraco.Forms.Core.FieldPreValueSource.
Umbraco.Deploy.Exceptions.ProcessArtifactException: ProcessInit failed for artifact umb://forms-prevalue/feea6b94324f4295800fc9db2f557c63.
 On: <umb://forms-prevalue/feea6b94324f4295800fc9db2f557c63>
Umbraco.Deploy.Exceptions.RemoteApiException: The remote API has thrown an exception.
-- UDIS --------------------------------------------------------
<umb://forms-prevalue/feea6b94324f4295800fc9db2f557c63>
----------------------------------------------------------------

EXCEPTION:

Umbraco.Deploy.Exceptions.RemoteApiException: The remote API has thrown an exception.
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<SucceedOrThrow>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<WaitAction>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Environments.RemoteUmbracoEnvironment.<ProcessPackageAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.DeployRestoreWorkItemBase.<ProcessPackage>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__15.MoveNext()

REMOTE:
Umbraco.Deploy.Exceptions.ProcessArtifactException: ProcessInit failed for artifact umb://forms-prevalue/feea6b94324f4295800fc9db2f557c63.

   at Umbraco.Deploy.Environments.CurrentEnvironment.<>c__DisplayClass22_0.<ProcessArtifacts>b__0(IArtifact x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)
   at Umbraco.Deploy.Environments.CurrentEnvironment.ProcessPackageAsync(Guid sessionId, Package package, CancellationToken token)
   at Umbraco.Deploy.Environments.EnvironmentController.<>c__DisplayClass13_0.<<BeginProcessPackage>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SessionWorkItem.<ExecuteAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Umbraco.Deploy.Work.WorkItems.SessionWorkItem.WaitIdle()
   at Umbraco.Deploy.Environments.EnvironmentController.WaitIdle(SessionActionModel model)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--> System.InvalidOperationException: Don't know how to map Umbraco.Deploy.Forms.Artifacts.PreValueSourceArtifact to Umbraco.Forms.Core.FieldPreValueSource.

   at Umbraco.Core.Mapping.UmbracoMapper.Map[TSource,TTarget](TSource source, TTarget target, MapperContext context)
   at Umbraco.Deploy.Forms.ServiceConnectors.PreValueSourceConnector.ProcessInit(PreValueSourceArtifact art, IDeployContext context)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ServiceConnectorBase`3.ProcessInit(IArtifact art, IDeployContext context)
   at Umbraco.Deploy.Environments.CurrentEnvironment.<>c__DisplayClass22_0.<ProcessArtifacts>b__0(IArtifact x)

```
I have already posted this in the forms issues https://github.com/umbraco/Umbraco.Forms.Issues/issues/337, but Tim thinks it is a deploy issue.

Yours
Dirk

**Comment by AndyButland** [comment] 2021-03-25 11:55
I've tested this on Deploy 4.1.0 and find that form prevalues can be deployed, so believe this has been fixed.  The previous comment also suggests this was resolved in an earlier version, so will close.

**Closed by AndyButland** 2021-03-25 11:55 UTC
Labels: state/needs-investigation, type/bug

**Comment by aaronshelbySBA** [comment] 2021-08-12 14:00
I'm using Umbraco Forms 8.3.1, and experiencing this same problem. However the workaround suggested by ronaldbarendse doesn't seem to work. Umbraco support recommended that I reopen this issue. 

In my case, the problem is not in deployment but in running a local cloned copy of our production environment. The first run results in the error:
-------------------------
An error occurred
The source environment has thrown a Umbraco.Deploy.Exceptions.ProcessArtifactException with message: ProcessInit failed for artifact umb://forms-prevalue/01548fa656344800b2366536d898b6f3. It might have been caused by an inner System.InvalidOperationException with message: Property Umbraco.Forms.Core.Interfaces.IFieldPreValueSource.Name : System.String does not have a setter.

The following artifacts might be involved:

umb://forms-prevalue/01548fa656344800b2366536d898b6f3
The technical details may contain more information.

Time: Thu Aug 12 2021 06:56:34 GMT-0700 (Mountain Standard Time)
-------------------------

I have applied the workaround to the UmbracoDeploy.Settings.config file in both my local clone and in the production environment. I have restarted both. But I still get the same error.

**Comment by aaronshelbySBA** [comment] 2021-08-12 15:30
@AndyButland I'm working with my team to get that patch in place but I expect that to take a while for them to get to it, and this is holding me up from completing my work. I was hoping to find a way to make the workaround work in the mean time. Any idea why it isn't working?

**Comment by AndyButland** [comment] 2021-08-13 06:45
I'm afraid not, would have to try to replicate your setup to see.  What version of Deploy are you on too please?

Meantime you may also be able to set `<forms transferFormsAsContent="false" />` which I believe should prevent trying to restore forms via the back-office, and might then get you over what's blocking you.

**Comment by aaronshelbySBA** [comment] 2021-08-13 13:19
I'm not sure. Umbraco Deploy isn't listed as an installed package in our live (Cloud) environment. How can I tell what version we're using?

**Comment by AndyButland** [comment] 2021-08-13 13:43
I believe it should show on your Cloud portal:
![image](https://user-images.githubusercontent.com/1993459/129366291-0989b7c2-846d-4ac6-a9c8-77b6d709d050.png)

**Comment by aaronshelbySBA** [comment] 2021-08-13 13:45
Ah. Yes it does. Umbraco Deploy 4.1.3.

**Comment by AndyButland** [comment] 2021-08-20 09:05
I've found time this morning to recreate your setup and have a further look at this.

Firstly, I've verified that a "setter" was added to this interface property `IFieldPreValueSource.Name` in Forms 8.5.  As of Deploy 4.1.3, it's looking and expecting that setter to exist, and hence one way to resolve the problem would be to upgrade to at least this minor version.  This is further than the latest patch of 8.3 as I advised earlier (there were some compatibility fixes applied in that release, but not this particular one).  If you can, I'd suggest it's worth doing that, and even better to the latest version of Forms, as you'd benefit from further features and bug-fixes.

I have then tested the workaround Ronald noted above, and that does seem to work for me using the same dependencies that you have.  What this does is exclude the "Form Prevalues" from being restored.

So just to make sure we're doing the same, the file I have updated is `config\UmbracoDeploy.Settings.config`, to the following:

```
<?xml version="1.0" encoding="utf-8"?>
<settings>
    <excludedEntityTypes>
        <add type="forms-prevalue" />
    </excludedEntityTypes>
    <forms transferFormsAsContent="true" />
</settings>
```

I've applied this on both the source and the destination environment.

With that in place I can successfully run a "Full restore" operation from the back-office.  Without it, I hit the error you describe when I'm running against Forms 8.3.

And then lastly the issue itself looks like we can fix in Deploy for those like you running older versions of Forms - although the interface property `IFieldPreValueSource.Name` doesn't have a setter, the concrete type `FieldPreValueSource.Name` does - so looks like we can check for and use that when restoring form prevalues.  I'll get that arranged for an upcoming release.

**Comment by aaronshelbySBA** [comment] 2021-08-20 19:32
Thank you. I'm running into additional problems, but I don't think they're related to this bug.

On a fresh clone of the live environment, when I run the site's root path (http://localhost:55423/), it automatically attempts a restore that still fails with:

> The source environment has thrown a Umbraco.Deploy.Exceptions.ProcessArtifactException with message: ProcessInit failed for artifact umb://forms-prevalue/01548fa656344800b2366536d898b6f3. It might have been caused by an inner System.InvalidOperationException with message: Property Umbraco.Forms.Core.Interfaces.IFieldPreValueSource.Name : System.String does not have a setter.

But I did try to do the full restore from the backoffice and I'm getting numerous schema mismatches. In addition all the document types and templates are missing in my local copy (no idea why) - which I believe is the reason for the schema errors.
