### ISSUE TITLE
Images are displaying as deleted after content transferring 

### ISSUE THREAD

**Issue by AndreyKarandashovUKAD** [umbraco/Umbraco.Deploy.Issues#58] opened 2021-06-16 09:57 UTC
Reproduction
------------
I've migrated from Old Media picker to Media Picker v3
and now when I'm transferring the content with new media picker - new images are not transferred. (displays as "deleted").

### Specifics

Umbraco version: 8.14.0
Umbraco Deploy version: 4.1.2
Umbraco.Deploy.Contrib.Connectors version: 3.0.3

### Steps to reproduce
1. Open the page with Media Picker v3
2. Upload new image
3. Try to move this page from stage to production
4. Image is missing in new media picker

1. https://i.imgur.com/pXrEm58.png
2. https://i.imgur.com/9HWiW02.png
3. https://i.imgur.com/D5U3RoQ.png
4. https://i.imgur.com/25vR0Iw.png
### Expected result

Image should be transferred to production
### Actual result
Image displays as deleted.

### Workaround 

Transfer all media before you transferring a content.

**Comment by AndyButland** [comment] 2021-06-16 14:10
Thanks for reporting @AndreyKarandashovUKAD - I can replicate.  The issue is that we are missing a "value connector" in deploy for this new property editor, that's responsible for ensuring the picked media is also transferred.  I've added it now in the linked PR, so this will be available in an upcoming release.  In the meantime the workaround you've noted is the correct action to take.

**Comment by AndreyKarandashovUKAD** [comment] 2021-06-16 14:21
@AndyButland I've also seen strange behavior with the old media collector, but can't reproduce it.
The message was something like this:
Schema mismatch: (Not sure about this), but the message was:
"It is impossible to transfer media picker (obsolete)"
But I can't reproduce anymore.

It was early morning and I forgot to take a screenshot.

Thanks for the fix, I hope it'll be released soon.

**Comment by AndyButland** [comment] 2021-07-06 05:37
This missing value connector has been added now and will be available in the next release.

**Closed by AndyButland** 2021-07-06 05:37 UTC
Labels: release/4.2.0

**Comment by hfloyd** [comment] 2021-08-04 21:12
I just came across this issue today. @AndyButland Any ETA for the 4.2.0 release?

**Comment by AndyButland** [comment] 2021-08-05 05:43
In the next few weeks I'm hoping.  Sorry, I can't be more specific than that at the moment as we're still reviewing code for some parts, have testing to do and need to arrange deployments to Cloud.

**Comment by hfloyd** [comment] 2021-08-05 16:21
Thanks, @AndyButland 😊
