### ISSUE TITLE
Errors when trying to restore / transfer content

### ISSUE THREAD

**Issue by dawoe** [umbraco/Umbraco.Deploy.Issues#128] opened 2022-06-23 16:18 UTC
Hi,

We can't restore or transfer content on Umbraco Cloud at the moment. This happens even if we want to transfer one item.

After the restore or transfer has been in progress for a while we get the following error :

```
Umbraco.Deploy.Infrastructure.Exceptions.RemoteApiException: The remote API did not return application/json content.
   at Umbraco.Deploy.Infrastructure.Environments.RemoteUmbracoEnvironment.SucceedOrThrow(HttpResponseMessage result, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Environments.RemoteUmbracoEnvironment.BeginSessionAsync(Guid sessionId, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.DeployRestoreWorkItemBase.GetSessionOn(IUmbracoEnvironment env)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.TargetPartialRestoreWorkItem.ExecuteAsyncSub(IWorkContext context, List`1 resume, CancellationToken token)
```

We have these settings for Deploy : 

```
 "Deploy": {
      "Settings": {
        "IgnoreBrokenDependencies": true,
        "DatabaseCommandTimeout": "0.0:59:00",
        "HttpClientTimeout": "0.0:59:00",
        "SessionTimeout": "0.0:59:00",
        "SourceDeployTimeout": "0.0:59:00"
      }
    }
```

But we are getting the error way before the time out is reached.

**Comment by dawoe** [comment] 2022-06-23 16:42
Umbraco CMS 9.5.1 and Deploy 9.4.0

And yes we are using Block list

**Comment by RyuLindow** [comment] 2022-06-23 16:48
Hmm, interesting.

We've seen the exact same issue on a different project earlier this week but that case got a bit railroaded and I didn't get much further with it outside of narrowing it down a bit.

Could you please reach out to support if you already haven't and ask them to escalate it to 2nd lvl? Feel free to link this thread too :)

I would like to attach Deploy's source code and debug it from there.

**Comment by RyuLindow** [comment] 2022-06-23 16:51
Ah, actually, please check if you're on 9.0.1 before you reach out to them `https://www.nuget.org/packages/Umbraco.Deploy.Contrib/9.0.1`

**Comment by dawoe** [comment] 2022-06-23 17:10
I am using contrib 9.0.1

**Comment by dawoe** [comment] 2022-06-23 17:17
Just want to check out if it is not related to redirects we have in place.

If that is not the case. I will create a support ticket through zendesk

Dave

**Comment by RyuLindow** [comment] 2022-06-23 17:19
From what I remember redirects were concluded to not be relevant to the issue in the other projects I've mentioned.

**Comment by dawoe** [comment] 2022-06-23 19:38
Hi @RyuLindow 

Some of our redirect seemed to be the problem 

After adding the condition below to them I was able to restore multiple times without problems.

` <add input="{REQUEST_URI}" negate="true" pattern="^/umbraco" />`

So I will close this one.

**Comment by RyuLindow** [comment] 2022-06-23 19:54
Okay, that was unexpected but I'm glad that you got it working!

**Comment by bjarnef** [comment] 2022-06-24 22:11
I have same issue on a project, but not while the project was on v9.2.0 but after upgrading to latest v9.5.2
Umbraco.Deploy.Contrib was on v9.0.0, but has been upgraded to v9.0.1 as well.

We haven't any redirects yet.

I was able to restore from Live to Development after adding this:

```
"Deploy": {
      "Settings": {
        "IgnoreBrokenDependencies": true
      }
}
```

However I still have same issue restoring from Development to Local environment.

I tried increasing the timeouts from 20 to 30 minutes, but didn't help.
It a pretty standard Umbraco project, so 30 minutes should be sufficient to restore.

**Comment by RyuLindow** [comment] 2022-06-25 18:02
Does it time up after 30min or much faster than that?

**Comment by bjarnef** [comment] 2022-06-25 18:37
@RyuLindow it times up within ten minutes.

**Comment by RyuLindow** [comment] 2022-06-25 20:36
Okay, it sounds exactly like the other project I mentioned earlier.

Could you please reach out to support with this and ask for the case to be escalated?

I'm really curious about this one and if it's a bug in 9.5.x then we, obviously, want to get it fixed :)

**Comment by bjarnef** [comment] 2022-06-25 20:41
Yes, I already did ;)
I talked with Sergiu about this, who mentioned this issue as well and escalated it to the developers, but probably first on monday.

But I just wanted to post my findings here as well.

Strange enough I was able to restore to Development environment, but not to local environment, which makes it difficult to continue upgrade to Umbraco 10 following the guide here: https://our.umbraco.com/documentation/Umbraco-Cloud/Upgrades/Upgrading-from-9-to-10/

**Comment by RyuLindow** [comment] 2022-06-25 20:43
Oh, I found the ticket. Will look into it on Monday :)

**Comment by AndyButland** [comment] 2022-06-29 09:33
Just to record I did a test with this today, git cloned the live environment, built and run, restored the doc types and then went to the back-office.  Did a "Tree Restore" under "Content" and it all came down OK without errors.

In passing it was noted to me that the "Partial Restore" option is missing from the content root.  This is a bug (changes were made in the last release and something missed merging up from Deploy 4 to Deploy 9).  It's fixed and will be resolved with the next patch release.

**Comment by bjarnef** [comment] 2022-07-06 12:00
@AndyButland a few times I got in working to restore content to local environment, but mostly I get the abort session message.

![image](https://user-images.githubusercontent.com/2919859/177544816-877d0939-a865-420e-b0c8-3ab5c07422cd.png)

It seems to work better when restoring on Development from Live.

Btw. when you accidentally close the dialog, there is no way to follow the progress, so one just have to want until in finished.
Would it be possible always to show the restore progress in e.g. Deploy dashboard in content section?

**Comment by hfloyd** [comment] 2022-07-08 21:08
I just came across this today trying to create a fresh DB copy from Development to Local. The Local DB is SQL Server. 

**Versions:**

- Umbraco 9.5.2
- Forms 9.4.2
- Deploy 9.4.0
- Umbraco Id
- Umbraco.Deploy.Contrib 9.0.1

RE: 
> In passing it was noted to me that the "Partial Restore" option is missing from the content root. This is a bug (changes were made in the last release and something missed merging up from Deploy 4 to Deploy 9). It's fixed and will be resolved with the next patch release.

Yes, I noticed that also. I am trying to do a Tree restore on Content, the message I see is "Abort remote session" and once it finally finishes up and shows the full error:


**An error occurred**
**The source environment has thrown a Umbraco.Deploy.Infrastructure.Exceptions.RemoteApiException with message: The remote API did not return application/json content. It might have been caused by an inner with message: (empty)**

**The technical details may contain more information.**


```
35791224 - Executing, 10%
35791224 - Executing, 10% - Get remote session
35791224 - Executing, 80% - Exception!
35791224 - Executing, 80% - Abort remote session
35791224 - Executing, 80% - Restore caches and indexes
35791224 - Failed, 80% - Total time 00:08:19.343.

-- EXCEPTION ---------------------------------------------------
 (proper exception traces at the end of this log)
Umbraco.Deploy.Infrastructure.Exceptions.RemoteApiException: The remote API did not return application/json content.
----------------------------------------------------------------

EXCEPTION:

Umbraco.Deploy.Infrastructure.Exceptions.RemoteApiException: The remote API did not return application/json content.
   at Umbraco.Deploy.Infrastructure.Environments.RemoteUmbracoEnvironment.SucceedOrThrow(HttpResponseMessage result, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Environments.RemoteUmbracoEnvironment.BeginSessionAsync(Guid sessionId, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.DeployRestoreWorkItemBase.GetSessionOn(IUmbracoEnvironment env)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.TargetRestoreWorkItem.ExecuteAsyncSub(IWorkContext context, List`1 resume, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.TargetRestoreWorkItem.ExecuteAsyncSub(IWorkContext context, List`1 resume, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.TargetRestoreWorkItem.ExecuteAsync(IWorkContext context, CancellationToken token)

REMOTE:
TEXT: <html><head><title>500 - The request timed out.</title></head><body>  <font color ="#aa0000">         <h2>500 - The request timed out.</h2></font>  The web server failed to respond within the specified time.</body></html>
```
The last bit of HTML - "500 - The request timed out." gives me a clue what is happening, but I can't choose a smaller subset of Content to restore.

**Comment by KartikGolya24** [comment] 2022-07-29 10:12
Hi,

We can't restore or transfer content on Umbraco Cloud at the moment. This happens even if we want to transfer one item.

After the restore or transfer has been in progress for a while we get the following error :

34051a4b - Executing, 10% - Get remote session
34051a4b - Executing, 80% - Exception!
34051a4b - Executing, 80% - Abort remote session
34051a4b - Executing, 80% - Restore caches and indexes
34051a4b - Failed, 80% - Total time 00:07:41.825.
-- EXCEPTION ---------------------------------------------------
(proper exception traces at the end of this log)
Umbraco.Deploy.Infrastructure.Exceptions.RemoteApiException: The remote API did not return application/json content.
----------------------------------------------------------------
EXCEPTION:
Umbraco.Deploy.Infrastructure.Exceptions.RemoteApiException: The remote API did not return application/json content.
at Umbraco.Deploy.Infrastructure.Environments.RemoteUmbracoEnvironment.SucceedOrThrow(HttpResponseMessage result, CancellationToken token)
at Umbraco.Deploy.Infrastructure.Environments.RemoteUmbracoEnvironment.BeginSessionAsync(Guid sessionId, CancellationToken token)
at Umbraco.Deploy.Infrastructure.Work.WorkItems.DeployRestoreWorkItemBase.GetSessionOn(IUmbracoEnvironment env)
at Umbraco.Deploy.Infrastructure.Work.WorkItems.TargetRestoreWorkItem.ExecuteAsyncSub(IWorkContext context, List`1 resume, CancellationToken token)
at Umbraco.Deploy.Infrastructure.Work.WorkItems.TargetRestoreWorkItem.ExecuteAsyncSub(IWorkContext context, List`1 resume, CancellationToken token)
at Umbraco.Deploy.Infrastructure.Work.WorkItems.TargetRestoreWorkItem.ExecuteAsync(IWorkContext context, CancellationToken token)
REMOTE:
TEXT: <html><head><title>500 - The request timed out.</title></head><body> <font color ="#aa0000"> <h2>500 - The request timed out.</h2></font> The web server failed to respond within the specified time.</body></html>

**Comment by sotirisf** [comment] 2022-09-26 19:31
Having the exact same problem with 9.5.2 deploying a large set of nodes from local to live:

```
8bf120d0 - Failed, 80% - Total time 00:11:09.569.

-- EXCEPTION ---------------------------------------------------
 (proper exception traces at the end of this log)
Umbraco.Deploy.Infrastructure.Exceptions.RemoteApiException: The remote API did not return application/json content.
----------------------------------------------------------------

EXCEPTION:

Umbraco.Deploy.Infrastructure.Exceptions.RemoteApiException: The remote API did not return application/json content.
   at Umbraco.Deploy.Infrastructure.Environments.RemoteUmbracoEnvironment.SucceedOrThrow(HttpResponseMessage result, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Environments.RemoteUmbracoEnvironment.ProcessPackageAsync(Guid sessionId, Package package, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.DeployRestoreWorkItemBase.ProcessPackage(Package package)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.SourceDeployWorkItem.ExecuteAsync(IWorkContext context, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.SourceDeployWorkItem.ExecuteAsync(IWorkContext context, CancellationToken token)

REMOTE:
TEXT: <html><head><title>500 - The request timed out.</title></head><body>  <font color ="#aa0000">         <h2>500 - The request timed out.</h2></font>  The web server failed to respond within the specified time.</body></html>
```


I've updated umbracocloud.json with the following settings, deployed, restarted the target environment:

```
"Deploy": {
      "Settings": {
             "DatabaseCommandTimeout": "0.0:59:00",
        "HttpClientTimeout": "0.0:59:00",
        "SessionTimeout": "0.0:59:00",
        "SourceDeployTimeout": "0.0:59:00"
      }
    }

```

**Comment by hfloyd** [comment] 2022-10-17 22:38
Today I tried this again, after some updates:
**Current:**
Umbraco 9.5.4
Forms 9.5.2
Deploy 9.5.0
Umbraco.Deploy.Contrib 9.1.0

I'm attempting to restore from Cloud Development or Cloud Live to Local. 

If I do a **"Workspace Restore"**, I see the message "Create manifest on source", which seems to take a very long time, then I get "Abort remote session".

If I attempt a **"Partial Restore"** with a small section of Content, I see the message "Get remote session" for quite a long time, then I see "Abort remote session".


Has anyone solved this issue?

**Comment by hfloyd** [comment] 2022-10-18 15:29
Woo hoo! Today's release of Deploy 9.5.1 fixed it for me!

**Comment by AndyButland** [comment] 2022-10-19 13:44
Good to hear @hfloyd - we had some rework in this patch with regard to HTTP requests between environments (used in back-office transfers).

Otherwise just to respond more widely on this issue - at least the cases around failures when transferring a lot of content or media items - we've been investigating this and to briefly summarise, we seem to be hitting a timeout lower than that Deploy is configured with.  This looks to be due to [a hard limit on Azure App Services](https://stackoverflow.com/a/38676086/489433), that I believe we have started to run into since the update to new infrastructure.  

Unfortunately there doesn't look to be an easy solution to this.  There's no configuration we can set to increase this timeout from what I read, it's a fundamental restriction of the platform.

One thing we are working on to at least help with this is to the add the option to "page" the transfer requests,  In other words, one way around this is to do a bulk transfer in chunks, which you can do if for example you are deploying a number of media items in nicely structured folders.  But you can't do that currently if you have lot of nodes within a single folder (e.g. many media items, or many content items in a list view).  If we add the option when you choose to "include all descendants" to also be able to transfer "page X with page size of Y", that would at least allow these "chunked" deployment to be done and unblock transfers that currently can't be completed

There may be more fundamental changes we can make to how Deploy works for these bulk transfers that we will also consider.

**Comment by hfloyd** [comment] 2022-10-19 15:45
Hi @AndyButland , Thanks for the explanation. In terms of the "paging", it would be nice if Deploy could do the "chunking/paging" itself automatically, rather than make "transfer nodes 1-25, transfer nodes 26-50, transfer nodes 51-75..." additional steps that the back-office deployer has to manage.

**Comment by AndyButland** [comment] 2022-11-08 08:28
We are planning a patch release for next week that will introduce a configuration value, allowing for batching of content transfers.  Documentation PR explaining this is [here](https://github.com/umbraco/UmbracoDocs/pull/4546/files).

I'll close this issue now and tag it with the release numbers.  There's been quite a few comments on this issue, some resolved, some perhaps not, and not all are related to the problem identified in [the comment above](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/128#issuecomment-1284041385).  However I'll consider this issue now related to the particular case of trying to deploy a lot of content or media at once, and hitting this Azure service limit, for which we now have means of resolving.

Please feel free to open new issues if there are any further problems found in this area.

**Closed by AndyButland** 2022-11-08 08:28 UTC
Labels: release/4.7.2, release/9.5.2, release/10.1.2

**Comment by bjarnef** [comment] 2022-11-28 14:03
@AndyButland I have upgraded to latest Umbraco 10.3.2 and Deploy 10.1.2, but it seems I still get this error.

Besides that I have this:

```
```

**Comment by callumbwhyte** [comment] 2023-01-13 21:34
We've had this issue today on a moderate size Cloud site while restoring from live to dev and can't get around it...

Even with the new `SourceDeployBatchSize` set as low as 5 we still get the Azure timeout. For safe measure we also set the other timeouts ridiculously high.

```
"Deploy": {
  "Settings": {
    "IgnoreBrokenDependencies": true,
    "DefaultTimeoutSeconds": 86400,
    "SessionTimeout": "0.23:59:59",
    "SourceDeployTimeout": "0.23:59:59",
    "DatabaseCommandTimeout": "0.23:59:59",
    "HttpClientTimeout": "0.23:59:59",
    "DiskOperationsTimeout": "0.23:59:59",
    "SourceDeployBatchSize": 5
  }
}
```

This is on Umbraco v10.4 with Deploy v10.1.2. Result is the same whether it's a workspace or a partial restore.

**Comment by bjarnef** [comment] 2023-01-19 11:58
@AndyButland I still get this error on Umbraco v10.4.0 and Deploy v10.1.2

I tried to set `SourceDeployBatchSize` but didn't seem to help. It aborts the session and no content nodes has been restored.
It seems of often happens in an archive when one can't choose to restore part of the content nodes, but it is all or nothing.

```
"Deploy": {
  "Settings": {
    "IgnoreBrokenDependencies": true,
    "PreferLocalDbConnectionString": true,
    "DatabaseCommandTimeout": "0.0:59:00",
    "HttpClientTimeout": "0.0:59:00",
    "SessionTimeout": "0.0:59:00",
    "SourceDeployTimeout": "0.0:59:00",
    "SourceDeployBatchSize": 1000
  }
}
```

**Comment by AndyButland** [comment] 2023-01-19 12:57
Just to be clear here the `SourceDeployBatchSize` setting won't help with restores, it only takes effect for transfers upstream from a source environment.  We're seeing if we can do other things to improve the situation for large restores.

**Comment by bjarnef** [comment] 2023-01-19 13:30
@AndyButland thanks.. that would be great.
something that also seems odd, is when restoring a node without children/descendants and it doesn't have any dependencies to another nodes, it seems to be running for quite long time.

Not sure it the amount of content nodes in some way affects the process?

**Comment by bjarnef** [comment] 2023-01-19 18:33
@AndyButland let me know if you need access to this project, to reproduce the issues and make improvements 👍

**Comment by beingonlinedave** [comment] 2023-01-25 11:06
Just to add some experiences I have had in case it helps with the problem. 

I set SourceDeployBatchSize to 10 as an experiment but noticed when viewing the log on the remote web app that there were lots and lots of entries. I concluded that this is because in my root node I have Blocklists for the user to be able to create the navigation. The navigation is of multiple levels and there there are many items referenced from this root node. My deduction is that obviously when publishing a node it needs to publish everything referenced there and so the chain of references in my case means that a single publish creates a batch way beyond the 10 items specified. I'm not sure of how that could be solved other than somehow batching later in the process, which maybe it is already doing.

I was on with Umbraco Support and they suggested posting my experience. Hope this is of some use.

**Comment by Andrei-** [comment] 2023-02-03 11:55
Also got into this issue for the last week. I'm on Umbraco 10.4 with Deploy 10.1.2 in a cloud project.

**Comment by beingonlinedave** [comment] 2023-02-06 09:04
If it helps address the issue, the way I got a workable system was to complete my website on my staging environment i.e. build out all the pages, then restore that database to act as my live, then when doing transfers now it works fine. It seemed to not be able to cope when I was trying to transfer an entire content tree to an empty database.

**Comment by AndyButland** [comment] 2023-02-10 10:44
We've got some updates coming in the next patch releases for Deploy, due Tuesday 14th Feb for 8, 9 and 10, and the week after for Deploy 4 (for Umbraco 8), that we expect to make some important improvements to deploy restore and transfer operations.  It's going to be difficult to say that all issues will be resolved, as unfortunately we are still limited by this hard cut-off imposed by Azure web apps, but we've been able to find quite a few optimisations to the process.  I've been testing with fairly large customer site that was having trouble restoring due to gateway timeouts, but with a combination of the improvements made, have found it now can.

Specifically you should see:

- A new tasks to "Set signatures" via the backoffice settings dashboard. Triggering this will include these representations of each entity are are calculated and cached before a restore is commenced. These are generated as part of a restore operation if they don't exist, but that can take some time. By doing this in advance, and on a background process, it will complete and ensure this step isn't needed as part of the restore operation itself.  These signatures are kept up to date as content and other items are saved in Umbraco, but it's possible they have been cleared and so we don't have a full representation.
 - Provided a configuration option to allow for use of the media file metadata instead of file contents when calculating a checksum.  This is set via `Umbraco:Deploy:Settings:MediaFileChecksumCalculationMethod`.  The default value which preserves the existing behaviour is `PartialFileContents`. The new option is `Metadata` which instead of using the initial bytes of the file itself, just uses metadata (the file name and length). Particularly with blob storage, this is faster, and as far as I can see the only downside being a marginal, but still unlikely, increased chance of Deploy considering a media file hasn't changed when it has, and thus omitting it from the deployment.
 - Made a new default behaviour which can be tweaked via configuration, of loading all relations into memory once we know we are processing a lot of artifact signatures, and doing look-ups for the relations for each entity from there.  This can also be tweaked in configuration via `Umbraco:Deploy:Settings:NumberOfSignaturesToUseAllRelationCache`.
 - Optimised the retrieval of relations ensuring excluded relation types aren't retrieved and then filtered in memory.
 - Updated the default configuration to exclude the document/media "dependency" relations that were introduced in an earlier minor version of Umbraco 10 and 11, and aren't required for including in deployment operations.
 - I'm not sure how widespread this issue is, but the customer site I was testing on would error with "path too long" messages, as they had some PDFs with particularly long file names. This can happen between a local Windows file system and a remote system based on blob storage.  So have also added a  configuration value to allow continuing on these exceptions with media files (so the media item will be created, but with no file attached). This might be fine if you are developer restoring locally for example, and you don't care too much about a few missed media files.  This is set via `Umbraco:Deploy:Settings:ContinueOnMediaFilePathTooLongException`
 - Finally, there's now a custom message in the case of a hosting environment hard timeout with information and links to these options for resolution.
 
This will all be documented at the pages for [troubleshooting](https://docs.umbraco.com/umbraco-deploy/troubleshooting) and [configuration](https://docs.umbraco.com/umbraco-deploy/deploy-settings) for Deploy (the changes will be live on Tuesday 14th Feb, meantime here's a [link to the PR](https://github.com/umbraco/UmbracoDocs/pull/4905) with the changes).

**Comment by hfloyd** [comment] 2023-02-10 17:43
@AndyButland Woohoo! This all sounds amazing! What a nice Valentine from the Cloud Team 💕

I have bumped up against the "file path too long" issue as well sometimes... I thought I had created an issue suggesting that the Media section should help with that by truncating filenames on upload if they exceed a certain length, but I can't find the post anywhere....

**Comment by bjarnef** [comment] 2024-01-19 15:25
@AndyButland not sure if this is still an issue on Umbraco Cloud 
Umbraco 13.0.3
Forms 13.0.1
Deploy 13.0.3

```
"Deploy": {
  "Settings": {
    "ContinueOnMediaFilePathTooLongException": true,
    "IgnoreBrokenDependencies": true,
    "IgnoreBrokenDependenciesBehavior": "All",
    "PreferLocalDbConnectionString": true,
    "DatabaseCommandTimeout": "0.1:30:00",
    "HttpClientTimeout": "0.1:30:00",
    "SessionTimeout": "0.1:30:00",
    "SourceDeployTimeout": "0.1:30:00",
    "DiskOperationsTimeout": "0.0:20:00"
  }
}
```

When I transfer from local to development I get this error:

![image](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/2919859/ec072511-8fb3-4241-8582-5d41644cd4c0)

but it run for less than 10 minutes before aborting session.

```
d17ff328 - Failed, 80% - Total time 00:07:40.393.
```

Often just frontpage node, but mostly it have references to content and/or media via pickers.

**Comment by bjarnef** [comment] 2024-01-22 14:16
@AndyButland anything else we can do about this? 🙈

![image](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/2919859/38aa7562-449f-4449-a775-b6e59b2be00c)

I can invite you to the Umbraco Cloud project and send a backup of the migrated database if you want to debug further 😎

**Comment by AndyButland** [comment] 2024-01-22 14:43
I assume you've already looked through the [troubleshooting page](https://docs.umbraco.com/umbraco-deploy/troubleshooting/) for these platform timeout issues.  One thing that's not noted there - but will be after [this PR](https://github.com/umbraco/UmbracoDocs/pull/5792) is merged - is the possibility to look at using the new [import/export feature](https://docs.umbraco.com/umbraco-deploy/v/12.deploy.latest/deployment-workflow/import-export).  We've found in testing that that it is less likely to run into this issue as it's not doing ongoing communication between the two environments and so can be more suitable for large transfers.

That's also a way of seeing what related a particular item is picking up and trying to deploy along with your selected item, as you'll see the related nodes also exported into the zip archive.  So that might also show if and why the transfer is "bigger" than you might have expected.

**Comment by bjarnef** [comment] 2024-01-22 19:46
@AndyButland I tried the export feature... at first it seems to be hanging for at while, but not it appears right away.

When importing to development, it seems to be missing a progress state?

![image](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/2919859/d3fd5bf3-abee-4d88-b893-48a1e3275545)
