### ISSUE TITLE
Mismatches when deploying content from local to live

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Deploy.Issues#72] opened 2021-09-30 11:14 UTC
I am migration a site from Umbraco v8 to v9 and cloned a clean Umbraco 9 project on Cloud.
Locally this it pointing to v8 database, generate revisions and deployed this, which are also extracted on the v9 project.

The revisions on local and live are identical, but I still get this error when deploying the content from local to live environment.

![image](https://user-images.githubusercontent.com/2919859/135444716-b8d24a2e-8bd8-4edb-89c9-4172ea22ba60.png)

![image](https://user-images.githubusercontent.com/2919859/135444774-7a651859-98cb-41cf-b037-572002a3c95b.png)

Strange enough this operation here seems to change the order of the dependencies compared to when I run `echo > deploy-export` or save from backoffice.

![image](https://user-images.githubusercontent.com/2919859/135444919-efce417c-7a5b-4767-9e33-fdb419c9aa28.png)

![image](https://user-images.githubusercontent.com/2919859/135445099-2b0394c4-d715-40ef-90aa-ae2c24c2efed.png)

But I guess the order shouldn't matter.

One thing it that the two "Settings" element types mentioned in the error message both inherits background color and text color properties from a "Base Color Theme" element type, but I don't see why that should be an issue.

Regarding the templates I don't see any differences except Umbraco Cloud transform these to lowercase in `/site/wwwroot/Views`  ... e.g. on local and in repository it is `HomePage.cshtml`, but `homepage.cshtml` in `/site/wwwroot/Views`

The error message doesn't tell anything about what the issue is and "See 'Mismatches' for details." isn't very helpful, when you check all revisions and confirm they are identical 😅

**Comment by bjarnef** [comment] 2021-09-30 11:39
@AndyButland do you have an idea why is causing these mismatches?

**Comment by bjarnef** [comment] 2021-09-30 13:16
I removed the un-checked the inherited composition from the two element types and added **Background Color** and **Text Color** properties directly to the setting element types instead.

It didn't use to be an issue, but many something in Deploy V9 that fails handling this?

Now I only have these template mismatches, but I can't figure out why?

![image](https://user-images.githubusercontent.com/2919859/135462206-87502435-a643-4d76-9879-fe92e73cfa86.png)

**Comment by bjarnef** [comment] 2021-09-30 21:37
Ohh, it seems like it may be a bug in Deploy v9.0.0, when templates has dependencies to a Master template.

I removed Master template for all these templates, pushed the revisions.. and now I can transfer the content to live/remote environment just fine 😲🤯

I haven't had this issue before with Deploy as far I recall only when there was mismatch on e.g. property or template aliases.

![image](https://user-images.githubusercontent.com/2919859/135532686-8a916650-e988-4288-bec5-aac63de8c9fa.png)

When I select Master template again for all templates, so I have this structure and deploy the revisions.

![image](https://user-images.githubusercontent.com/2919859/135533540-75988d3f-472a-485c-8cca-e591c8e9a1a4.png)

Afterwards I deploy again and get same error again:

![image](https://user-images.githubusercontent.com/2919859/135533368-0bbe4b23-3857-44d5-a330-b09d9d3445e2.png)

**Comment by bjarnef** [comment] 2021-09-30 21:38
@AndyButland @nul800sebastiaan I wonder if you guys could try if you can reproduce this error?

**Comment by bjarnef** [comment] 2021-09-30 22:19
When I switch the the connection string from pointing on the v8 database, to point to the original LocalDB created when cloning the clean Umbraco Cloud V9 project (empty connection string), then I get same error when doing a full restore from the live environment which contain the content nodes previous transferred.

![image](https://user-images.githubusercontent.com/2919859/135537284-787e9e11-ee15-449b-b7de-6f465b3d5651.png)

**Comment by jonat123** [comment] 2021-10-01 13:49
@bjarnef I can confirm that I am seeing the same issue with the master template and content transfers, when migrating a V8 site to a V9 site, so this does indeed look like a bug.

**Comment by AndyButland** [comment] 2021-10-01 15:04
Thanks both.  I've been trying to replicate this, but unfortunately without success.  Are either of you able to please validate what I'm doing to see if I'm missing something, or yourselves provide a set of steps, ideally for a single doc type/template to make it easier to diagnose, to trigger this issue please?

Here's what I've tried:

- On a V8 site running Umbraco Deploy, created a doc type with a template.
- Created another template and made that the master template for the first.
- Copied the 3 generated `.uda` files and the two `.cshtml` files into a local V9 environment, and triggered an extraction.
- Confirmed that I see the doc type and templates in the back-office as expected.
- Copied the `.uda` files and the `.cshtml` files into a destination V9 environment, and triggered an extraction.
- Created a content item based on the doc type in the local environment, and queued it for transfer.
- Successfully transferred the content item to the destination environment.

**Comment by bjarnef** [comment] 2021-10-01 17:55
@AndyButland just a few thought.

Could you name then master tenplate "Master" and with alias "Master". I didn't try renaming it to something else though.

When I migrated the site I switched the connection string in the new cloned v9 install to target the existing v8 database and ran `echo > deploy-export`.

Then I deployed the revisions and templates to v9 Cloud project and checked the document types and templates existed on the remote environment.

Finally I deployed the content (still with connection string target in v8 database) to the v9 remote environment in this case just the live environment.
Then I got the mismatch error.

Otherwise let me know and I can grant you access to the Cloud project I am working on. Maybe you have access to more log files or can debug on the specific project?

**Comment by AndyButland** [comment] 2021-10-04 08:12
Thanks - I can replicate this now having followed those steps.  So now just need to figure out what's going on...

**Comment by AndyButland** [comment] 2021-10-04 10:45
Some notes to keep track before breaking for lunch:

- This isn't consistent, but I have been able to see it with the setup described above:
    - Change template definitions on both sites so the template the document being transferred depends on doesn't have a master template - transfers OK.
    - Change template definitions on both sites so the template the document being transferred depends on **does** have a master template - fails with schema mismatch.
- When looking to debug, and having two local sites, one pointing to the same local database and the other two the same cloud database, I don't see an issue for either case.
- I do though when using the cloud site.
- Reviewing in the database can see the checksum saved in the signatures database is different when we have a master template associated.
- When generating checksums using known json strings can see the resulting checksum differs due to the order of the dependencies (and we only have two when we have a master template defined).
- It doesn't look like dependencies are explicitly ordered, so perhaps we have a framework change here that previously (i.e. in V8) always serialized in the order added.  But as we don't explicitly order, we can't guarantee that - and for some reason, running on Cloud we get one order, running locally we get another.
- A comment in the OP suggests there's other cases where we may get different orders.

**Comment by bjarnef** [comment] 2021-10-04 11:02
@AndyButland it makes sense if the checksum is generated based on the order of the dependencies.
I noticed as original mentioned here https://github.com/umbraco/Umbraco.Deploy.Issues/issues/72#issue-1012046011 when I had run `echo > deploy-export` and pushed changed, but then afterward used "Extract Schema To Data Files" operation locally or `echo > deploy-export` on Cloud environment and pulled changes, it seems to switch the ordering of the template dependencies.

If I locally ran `echo > deploy-export` multiple times after it didn't seem to cause changes or if I triggered "Extract Schema To Data Files" operation multiple times.

**Comment by AndyButland** [comment] 2021-10-04 13:38
I've created a PR to resolve this now - it's in CMS rather than Deploy though, and relates to differences in globalization settings between local Windows environment and that used in Azure Web Apps (and Umbraco Cloud).

**Comment by AndyButland** [comment] 2021-10-05 06:42
Closing as this will be resolved with CMS release 9.0.1.  Not tagging as it's a CMS release rather than a Deploy one.

**Closed by AndyButland** 2021-10-05 06:42 UTC

**Comment by bjarnef** [comment] 2021-10-05 06:50
@AndyButland I was wondering if is it possible as a workaround for now in Startup.cs to configurate default culture `en-US`, which I think is the default culture on Umbraco Cloud.
I tried something like this, but didn't seem to work :) https://stackoverflow.com/a/44888965/1693918

**Comment by AndyButland** [comment] 2021-10-05 06:57
I don't think that'll help, as it's not just related to the default culture.  It's related to this [change](https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu), about which there's a blog post [here](https://jimmybogard.com/mind-your-strings-with-net-5-0/).

If you look in the PR I created, Bjarke has made a [comment](https://github.com/umbraco/Umbraco-CMS/pull/11265#issuecomment-933657039) which suggests and amend to your project file you could try now.

**Comment by bjarnef** [comment] 2021-10-05 07:31
Okay, I see :)
I came across this https://docs.microsoft.com/en-us/dotnet/core/run-time-config/globalization and it seems there is something called `runtimeconfig.json`. I am not familiar with this though, so I am not sure when it is used.

I will give it a try using the suggestion from @bergmania

**Comment by ronmurp** [comment] 2021-10-06 11:06
Had a similar schema mismatch problem today (trial account, U9 site). 

With no content, push, pull, restore/transfer all worked ok - i.e. produce doc types in live or local doesn't matter.

Created a simple home page doc type with a **composition**, where composition contained a Page Title text string. 

Creating content home page, either on local first, then transfer, or live first, then restore locally, ... schema mismatch.

Finally, removed composition from home page doc type, and added page title as a property. Then restores/transfers start to work. Adding more properties, locally or live, with push or pull, transfer or restore, all worked.

The composition seemed to be the problem.
