### ISSUE TITLE
Conditionals on Forms do not transfer

### ISSUE THREAD

**Issue by RasmusUmbraco** [umbraco/Umbraco.Deploy.Issues#158] opened 2023-01-31 11:05 UTC
When transferring a Form with conditionals these are not sent to the target environment.

Reproduction:
1. Add a condition to a Form on the source environment
![image](https://user-images.githubusercontent.com/88326257/215742859-7b25fd12-926b-4c43-9af8-477a018debf9.png)
2. Transfer the Form to the target environment
3. The Form is missing the condition on the target environment
![image](https://user-images.githubusercontent.com/88326257/215743133-12bcc9a4-71d4-4403-822b-c477ebdb5330.png)

Tested on Cloud on these versions:
![image](https://user-images.githubusercontent.com/88326257/215743350-1c4769f9-ee47-4c02-8f2b-a7f11216621e.png)
It has also been reported on-premise on v11.

**Comment by AndyButland** [comment] 2023-01-31 11:08
Looks to be an issue since Deploy 4 (for Umbraco 8).  This "page condition" was introduced in Forms in 8.9, which is later than the Deploy dependency in that version.  We need to update the artifact creation and mapping to handle this additional field.

**Comment by beingonlinedave** [comment] 2023-01-31 11:22
Hi, to add to this, I encountered an issue with conditions on workflow items.

Steps to reproduce issue:

Create a form, add a Send email with template (Razor) workflow item and add a condition to it e.g. that it only runs if a value from a dropdown field is equal to a certain value. Then try and transfer that to another environment and see if the conditions are present in the other environment. In my experience it actually removed the conditions from the other environment, as I had manually added them based on it not working originally.

In this scenario, it is quite a problem as in my case I have about 10 different different emails that are set to go to different client support email address depending on the choices from dropdowns on the form. When it is transferred and all the conditions are not there, it sends an email to everyone of them meaning the customer will probably get 10 people getting in touch with them.

Hope this helps.

**Comment by AndyButland** [comment] 2023-01-31 11:46
Thanks for the additional information @beingonlinedave - we'll make sure workflow conditions, which are another feature introduced more recently in Forms than Deploy was aware of when the transfer of form information was built, are also included in the fix for this issue.

**Closed** 2023-02-01 05:58 UTC
Labels: release/4.7.3, release/9.5.3, release/10.1.3, release/11.0.1
