### ISSUE TITLE
Property data for "Date Picker with time" (Umbraco.DateTime) not being transferred on Content node deployment

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco.Deploy.Issues#199] opened 2024-01-13 06:17 UTC
I have a DateTime property on a Document type. When I transferred a handful of nodes using that Doctype, the date property was blank on the Destination environment (Local to U.Cloud Live). No errors were reported, the data is just not present.

### Property:
![image](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/1252593/60fd5461-0193-4e32-ada7-013971ca4fa4)

### Local Content:
![image](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/1252593/99e04ffb-90c0-4db4-ae84-88164acd05c3)

### Cloud Content:
![image](https://github.com/umbraco/Umbraco.Deploy.Issues/assets/1252593/fe368c76-b74f-46f3-94a9-4bdb92247a3b)

The property was marked as "Mandatory", so I turned that off, to see if it was the issue, but no change in deploy result. 

### Versions:
Umbraco 10.8.3
Deploy 10.3.2

**Comment by AndyButland** [comment] 2024-01-13 13:33
You should find this fixed in [the latest patch release](https://docs.umbraco.com/umbraco-deploy/v/10.deploy.latest/release-notes#version-10) @hfloyd - out on NuGet now and scheduled for auto-upgrade on Cloud on Tuesday.  Was also the cause of [this issue](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/195).

**Closed by AndyButland** 2024-01-13 13:33 UTC

**Comment by hfloyd** [comment] 2024-01-13 16:51
Awesome! Thanks, @AndyButland
